@extends('layouts')

@section('content')
    @include('landingSection.hero')
    @include('landingSection.oceanWave')
    @include('landingSection.features')
    @include('landingSection.whyChoose')
    @include('landingSection.socialMedia')
    @include('landingSection.prokolpoMap')
    @include('landingSection.infoSection')
    @include('landingSection.discountOffers')
    @include('landingSection.news')
    @include('landingSection.priceList')
    @include('landingSection.visitBooking')
    @include('landingSection.galary')
    @include('landingSection.videoSection')
    @include('landingSection.testimonial')
    @include('landingSection.otherProject')
    @include('landingSection.events')
    @include('landingSection.chairman')
    @include('landingSection.faq')
    @include('landingSection.contact')
    @include('landingSection.partners')

@endsection